---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзин
  
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  
implicit:
  - Пользователь должен иметь возможность удалять товар из корзины и увеличивать количество единиц товара в корзине
  - Пользователь должен иметь возможность заказать товар и оплатить заказ
  - Мобильная версия сайта должна быть доступна на разных устройствах
  - Сайт должен быть способен обрабатывать большое количество заказов
  - Магазин должен быть создан как SPA приложение
  - Вывод отфильтрованных в поиске товаров должен быть постраничным
  - Собранная корзина должна храниться в сессии браузера
