---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре, с помощью постраничного вывода
- На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
- Пользователь должен иметь возможность удалять товар из корзины и увеличивать количество единиц товара в корзине
- На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты. 
- Корзина хранится в сессии браузера

non-functional:
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть доступен на различных устройствах
- Сайт должен иметь мобильную версию
- Сайт должен быть разработан с помощью адаптивной верстки, чтобы он был удобным на мобильных устройствах
- Магазин должен быть SPA приложением, которое не перезагружает страницу  
 
implicit:
- Пользователь не может редактировать описание товара
- Сайт должен быть способен обрабатывать большое количество трафика
- Сайт должен быть способен обрабатывать большое количество заказов
- При добавлении товаров в корзину, иконка корзины должна изменяться, чтобы было понятно, сколько добавлено товаров
- При клике на фото товара оно должно увеличиваться до полноразмера
